version: "3.8"
services:

    nodeserver:
        container_name: node
        build:
            context: ./node
        entrypoint: wait-for database:3306 -t 40 -- ./start.sh
        networks:
          - nodenet
        ports:
          - "3000:3000"
        depends_on:
          - database

    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: dockerfile.prod
        networks:
          - nodenet
        ports:
            - "8080:80"

    database:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: database
      restart: always
      tty: true
      volumes:
        #- ./mysql:/var/lib/mysql
        - ./database:/docker-entrypoint-initdb.d/
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - nodenet

networks:
  nodenet:
    driver: bridge